### ISSUE TITLE
ModuleNotFoundError: No module named 'pystray' (?)

### ISSUE THREAD

**Issue by OneDefauter** [OwOHamper/lolesports.com-watcher#4]
```
F:\Downloads\lolesports.com-watcher>pip install -r requirements.txt
Collecting schedule==1.1.0
  Using cached schedule-1.1.0-py2.py3-none-any.whl (10 kB)
Collecting pystray==0.17.3
  Using cached pystray-0.17.3-py2.py3-none-any.whl (46 kB)
Collecting selenium==3.141.0
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting Pillow==9.1.0
  Using cached Pillow-9.1.0-cp39-cp39-win_amd64.whl (3.3 MB)
Requirement already satisfied: six in c:\users\defau\appdata\local\programs\python\python39\lib\site-packages (from pystray==0.17.3->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: urllib3 in c:\users\defau\appdata\local\programs\python\python39\lib\site-packages (from selenium==3.141.0->-r requirements.txt (line 3)) (1.26.6)
Installing collected packages: selenium, schedule, Pillow, pystray
Successfully installed Pillow-9.1.0 pystray-0.17.3 schedule-1.1.0 selenium-3.141.0

F:\Downloads\lolesports.com-watcher>main.py
Traceback (most recent call last):
  File "F:\Downloads\lolesports.com-watcher\main.py", line 7, in <module>
    import systray
  File "F:\Downloads\lolesports.com-watcher\systray.py", line 1, in <module>
    import pystray
ModuleNotFoundError: No module named 'pystray'
```

```
F:\Downloads\lolesports.com-watcher>pip list
Package            Version   Editable project location
------------------ --------- -------------------------
async-generator    1.10
attrs              22.1.0
captcha-solver     0.1.5
certifi            2022.9.24
cffi               1.15.1
charset-normalizer 2.1.1
EasyProcess        1.1
entrypoint2        1.1
exceptiongroup     1.0.0rc9
future             0.18.2
h11                0.14.0
idna               3.4
MouseInfo          0.1.3
mss                6.1.0
numpy              1.23.3
ocr-copy           0.1.0     f:\downloads\ocr-copy
outcome            1.2.0
packaging          21.3
Pillow             9.1.0
pip                22.2.2
PyAutoGUI          0.9.53
pycparser          2.21
pydub              0.25.1
PyGetWindow        0.0.9
pyglet             1.3.0
PyMsgBox           1.0.9
pynput             1.7.6
pyparsing          3.0.9
PyPasser           0.0.5
pyperclip          1.8.2
PyRect             0.2.0
pyscreenshot       3.0
PyScreeze          0.1.28
PySocks            1.7.1
pystray            0.17.3
pytesseract        0.3.10
pytweening         1.0.4
requests           2.28.1
schedule           1.1.0
selenium           3.141.0
setuptools         49.2.1
six                1.16.0
sniffio            1.3.0
sortedcontainers   2.4.0
SpeechRecognition  3.8.1
stem               1.8.0
trio               0.22.0
trio-websocket     0.9.2
urllib3            1.26.6
wsproto            1.2.0
xlib               0.21
```

```
F:\Downloads\lolesports.com-watcher>pip -V
pip 22.2.2 from c:\users\defau\appdata\local\programs\python\python39\lib\site-packages\pip (python 3.9)
```

I don't know much about Python, but isn't this "pip install -r requirements.txt" command supposed to install all modules/libs?

**Comment by teoobarca** [comment]
Maybe a bit late :D but try `python -m pip install -r requirements.txt`
